/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DeskRouteImport } from './routes/_desk'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as DeskIndexRouteImport } from './routes/_desk/index'
import { Route as DeskCardRouteImport } from './routes/_desk/card'
import { Route as DeskIntegrateRouteImport } from './routes/_desk/integrate'
import { Route as DeskIntelRouteImport } from './routes/_desk/intel'
import { Route as DeskJviRouteImport } from './routes/_desk/jvi'
import { Route as DeskScreenRouteImport } from './routes/_desk/screen'
import { Route as DeskSettleRouteImport } from './routes/_desk/settle'
import { Route as DeskTapeRouteImport } from './routes/_desk/tape'
import { Route as ApiBoardRouteImport } from './routes/api/board'

const DeskRoute = DeskRouteImport.update({
  id: '/_desk',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCardRoute = DeskCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => DeskRoute,
} as any)
const DeskIntegrateRoute = DeskIntegrateRouteImport.update({
  id: '/integrate',
  path: '/integrate',
  getParentRoute: () => DeskRoute,
} as any)
const DeskIntelRoute = DeskIntelRouteImport.update({
  id: '/intel',
  path: '/intel',
  getParentRoute: () => DeskRoute,
} as any)
const DeskJviRoute = DeskJviRouteImport.update({
  id: '/jvi',
  path: '/jvi',
  getParentRoute: () => DeskRoute,
} as any)
const DeskScreenRoute = DeskScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => DeskRoute,
} as any)
const DeskSettleRoute = DeskSettleRouteImport.update({
  id: '/settle',
  path: '/settle',
  getParentRoute: () => DeskRoute,
} as any)
const DeskTapeRoute = DeskTapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => DeskRoute,
} as any)
const ApiBoardRoute = ApiBoardRouteImport.update({
  id: '/api/board',
  path: '/api/board',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DeskIndexRoute
  '/embed': typeof EmbedRoute
  '/card': typeof DeskCardRoute
  '/integrate': typeof DeskIntegrateRoute
  '/intel': typeof DeskIntelRoute
  '/jvi': typeof DeskJviRoute
  '/screen': typeof DeskScreenRoute
  '/settle': typeof DeskSettleRoute
  '/tape': typeof DeskTapeRoute
  '/api/board': typeof ApiBoardRoute
}
export interface FileRoutesByTo {
  '/embed': typeof EmbedRoute
  '/card': typeof DeskCardRoute
  '/integrate': typeof DeskIntegrateRoute
  '/intel': typeof DeskIntelRoute
  '/jvi': typeof DeskJviRoute
  '/screen': typeof DeskScreenRoute
  '/settle': typeof DeskSettleRoute
  '/tape': typeof DeskTapeRoute
  '/api/board': typeof ApiBoardRoute
  '/': typeof DeskIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_desk': typeof DeskRouteWithChildren
  '/embed': typeof EmbedRoute
  '/_desk/card': typeof DeskCardRoute
  '/_desk/integrate': typeof DeskIntegrateRoute
  '/_desk/intel': typeof DeskIntelRoute
  '/_desk/jvi': typeof DeskJviRoute
  '/_desk/screen': typeof DeskScreenRoute
  '/_desk/settle': typeof DeskSettleRoute
  '/_desk/tape': typeof DeskTapeRoute
  '/api/board': typeof ApiBoardRoute
  '/_desk/': typeof DeskIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/embed'
    | '/card'
    | '/integrate'
    | '/intel'
    | '/jvi'
    | '/screen'
    | '/settle'
    | '/tape'
    | '/api/board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/embed'
    | '/card'
    | '/integrate'
    | '/intel'
    | '/jvi'
    | '/screen'
    | '/settle'
    | '/tape'
    | '/api/board'
    | '/'
  id:
    | '__root__'
    | '/_desk'
    | '/embed'
    | '/_desk/card'
    | '/_desk/integrate'
    | '/_desk/intel'
    | '/_desk/jvi'
    | '/_desk/screen'
    | '/_desk/settle'
    | '/_desk/tape'
    | '/api/board'
    | '/_desk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DeskRoute: typeof DeskRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  ApiBoardRoute: typeof ApiBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_desk': {
      id: '/_desk'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_desk/': {
      id: '/_desk/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/card': {
      id: '/_desk/card'
      path: '/card'
      fullPath: '/card'
      preLoaderRoute: typeof DeskCardRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/integrate': {
      id: '/_desk/integrate'
      path: '/integrate'
      fullPath: '/integrate'
      preLoaderRoute: typeof DeskIntegrateRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/intel': {
      id: '/_desk/intel'
      path: '/intel'
      fullPath: '/intel'
      preLoaderRoute: typeof DeskIntelRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/jvi': {
      id: '/_desk/jvi'
      path: '/jvi'
      fullPath: '/jvi'
      preLoaderRoute: typeof DeskJviRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/screen': {
      id: '/_desk/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof DeskScreenRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/settle': {
      id: '/_desk/settle'
      path: '/settle'
      fullPath: '/settle'
      preLoaderRoute: typeof DeskSettleRouteImport
      parentRoute: typeof DeskRoute
    }
    '/_desk/tape': {
      id: '/_desk/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof DeskTapeRouteImport
      parentRoute: typeof DeskRoute
    }
    '/api/board': {
      id: '/api/board'
      path: '/api/board'
      fullPath: '/api/board'
      preLoaderRoute: typeof ApiBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DeskRouteChildren {
  DeskCardRoute: typeof DeskCardRoute
  DeskIntegrateRoute: typeof DeskIntegrateRoute
  DeskIntelRoute: typeof DeskIntelRoute
  DeskJviRoute: typeof DeskJviRoute
  DeskScreenRoute: typeof DeskScreenRoute
  DeskSettleRoute: typeof DeskSettleRoute
  DeskTapeRoute: typeof DeskTapeRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskCardRoute: DeskCardRoute,
  DeskIntegrateRoute: DeskIntegrateRoute,
  DeskIntelRoute: DeskIntelRoute,
  DeskJviRoute: DeskJviRoute,
  DeskScreenRoute: DeskScreenRoute,
  DeskSettleRoute: DeskSettleRoute,
  DeskTapeRoute: DeskTapeRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DeskRoute: DeskRouteWithChildren,
  EmbedRoute: EmbedRoute,
  ApiBoardRoute: ApiBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
